### ISSUE TITLE
Saving to camera roll should check if media is image

### ISSUE THREAD

**Issue by olokobayusuf** [olokobayusuf/NatShare-API#37]
https://github.com/olokobayusuf/NatShare-API/blob/96dffa8d744276dd5090d74aa9c3b6cb34529552/iOS/NatShare/NatShare.m#L92-L109

**Comment by yosun** [comment]
https://gist.github.com/yosun/89f256b66141ec914e2b54c66c91c798

**Comment by olokobayusuf** [comment]
> https://gist.github.com/yosun/89f256b66141ec914e2b54c66c91c798

Thanks for this. But what actually needs to be done is to check if the media file at the given URL is an image or video, so that the correct one of `creationRequestForAssetFromImageAtFileURL` or `creationRequestForAssetFromVideoAtFileURL` will be called. `ShareMedia` doesn't handle only `GIF` files (as in your gist), it handles both image and movie files. I've already implemented the change.

**Comment by yosun** [comment]
Great, are you going to push this to the main, so that gif's recorded from NatCorder can be saved to album using NatShare?

**Comment by olokobayusuf** [comment]
Yup. I haven't yet tested if this will actually save the GIF to the Animated folder, I only expect that it does.

**Comment by olokobayusuf** [comment]
Changes are being implemented in #39

**Comment by yosun** [comment]
Hi! Just a note that the gif's are still not saved to Camera Roll on iOS

**Comment by olokobayusuf** [comment]
Are they not being saved to the camera roll at all? Or just not in the Animated folder?

**Comment by yosun** [comment]
The gif is being saved - it just does not make it to the Camera Roll / Animated folder. 

Also, all media is not making it to the album either...

**Comment by yosun** [comment]
Nevermind - it seems that the new iOS plugin files were not updated on Build and Run - and building in a new directory seems to have solved it.

**Comment by olokobayusuf** [comment]
Sounds good.
